### ISSUE TITLE
List actual optimal moves when computerFirst/computerSecond play wrong.

### ISSUE THREAD

**Issue by MichaelOultram** [uob-fp/fp#2]
I believe it should be as simple as adding ` ++ "\nAll optimal moves: " ++ (show $ map fst $ S.optimalMoves tree)` to the end of [TestHelpers.hs#L202](https://github.com/uob-fp/fp/blob/master/Exercise4/TestHelpers.hs#L202).

**Comment by JackeLee** [comment]
Good idea.
