### ISSUE TITLE
Test 6: testComputersA bug?

### ISSUE THREAD

**Issue by MichaelOultram** [uob-fp/fp#3]
If I've been given an empty 4x4 board, and I am the Horizontal player, then the optimal moves that I could play are (0,1), (0,2), (2,1) and (2,2). I choose the move (0,1) but the test bench says this is wrong. It says that the optimal moves are (1,0), (1,1), (1,2) or (1,3), at least according to the code I added in from #2. Even without my added code, I'm still having this issue.

As you might guess, it's kind of hard for me to debug my program when I think I am right. This is the only issue I'm having with the testbench. All other tests pass. I win in all of the AI tests against Random and Martin.

TestBench output extract:
````
Test 6: computerFirst, computerSecond (20 points)
  [testing] testComputers... ok.
  [testing] testComputersA... *** Failed!
Input: (PH,B2 (4,4) [] PH)
Exception: Found a non-optimal move M2 PH (0,1) in a play for the board B2 (4,4) [] PH
All optimal moves: [M PH(1,0),M PH(1,1),M PH(1,2),M PH(1,3)]
Expected output: ()
````
[View Full Output](https://gist.github.com/MichaelOultram/73ff92d4d3a426dcfe39)

**Comment by JackeLee** [comment]
It seems that your move (0,1) is really not optimal. Here you can find a reduced tree of B2 (4,4) [] PH: [link](https://gist.github.com/JackeLee/87bb4588ea9ad4f66388) (the tree is reduced to only losing branches and only up to fifth level).

As you can see, if the opponent plays (1,2) or (2,2), you'll lose.

**Comment by MichaelOultram** [comment]
Thanks @JackeLee, that helps a lot. Could you do another reduced tree but this time for one of the optimal moves (i.e. H plays (1,0)). This will give me something to compare with. In my head H can not win if V is also playing optimally so I need an example where H wins.

**Comment by JackeLee** [comment]
Sorry, I don't like doing something that you can do simply by writing ten lines of code. Why don't you write your own function that prints the tree together with outcomes for you (up to a certain depth if you wish)? It is an easy and important exercise to be able to do something like this! You can check that it works for trees of smaller boards and then use it for the board 4x4.

**Comment by MichaelOultram** [comment]
Okay, I managed to find out how H can win thanks to this [online domineering game](http://www.kongregate.com/games/ginoboby/domineering) and the tree trace (thanks for that). Turns out the game has more tactics than I first though. Time to "code it better".
